### ISSUE TITLE
Project coach details page error when loading again

### ISSUE THREAD

**Issue by fsdevocean** [PacktPublishing/Vue---The-Complete-Guide-incl.-Vue-Router-Vuex-and-Composition-API-#2]
In final project the coach details page works fine when loading for first time. If the page refresh it not working with throw an error. Specially coaches are not fetched from database.

![image](https://user-images.githubusercontent.com/19926369/180993852-ec90ad41-106c-4341-88c9-f5ffce1e944a.png)

**Comment by Sonakshis** [comment]
The way the project works, data is only loaded when visiting the root page of the project. If you reload the detail page, the data is missing. This is not Vue-specific - you could of course add such functionality but it’s not part of this project.
Hope this helps.
